name: functional_example

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  functional: 
    git:
      url: git://github.com/dhaval15/functional.git
      ref: master

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
