name: functional
description: A pure dart which helps varius functional paradigms.
version: 0.9.0
homepage: http://github.com/dhaval15/functional

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
