name: functional
description: A dart package which helps to use varius functional paradigms like function currying, piping.
version: 0.9.1
homepage: http://github.com/dhaval15/functional

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
